### PR TITLE
Updated tracking functionality plus some housekeeping

### PR DESCRIPTION
**Pull request by chris-steele**

### CODE REVIEW

**Comment by moloko** [comment]
presumably we can get rid of [this](https://github.com/cgkineo/adapt-contrib-confidenceSlider) once all this is sorted?

**Comment by moloko** [comment]
This is excellent, thanks Chris. If you could just do those minor changes we can get this merged then push it to the adaptlearning repo

**Comment by chris-steele** [comment]
Thanks @moloko - all done - the properties.schema has been updated with the translatable properties in https://github.com/chris-steele/adapt-contrib-confidenceSlider/pull/8

**Comment by chris-steele** [comment]
Both https://github.com/cgkineo/adapt-contrib-confidenceSlider and https://github.com/cgkineo/adapt-contrib-linkedConfidenceSlider can go.

**Pull request merged**
